# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da48af49f846343114109ab788ed98963825b85a6ce4974220f60afb4a059a7e463cdf53261d83e3d5b6b00db7e7f3bcc4b5ce36ce51c6f03c4814a689c6881c

test:
  secret_key_base: 93a496beb7fc1c849f7c7fcd4d162dfec3cb6709e74fccc250e6db759c4af0ac6d48cbc0a64e109ec06d0830413083aa8eeaf49a28d79878277602af9d602541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
